import { Router } from 'express';
import auth from './auth.js';
import seasons from './seasons.js';
import teams from './teams.js';
import players from './players.js';
import auctions from './auctions.js';
import bids from './bids.js';
import matches from './matches.js';
import scores from './scores.js';
import standings from './standings.js';
import statistics from './statistics.js';
import admin from './admin.js';
import users from './users.js';

const api = Router();
api.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
api.use('/auth', auth);
api.use('/seasons', seasons);
api.use('/teams', teams);
api.use('/players', players);
api.use('/auctions', auctions);
api.use('/bids', bids);
api.use('/matches', matches);
api.use('/scores', scores);
api.use('/standings', standings);
api.use('/statistics', statistics);
api.use('/admin', admin);
api.use('/users', users);
export default api;
